title: The bdverse
description: R package ensemble for biodiversity research
show_downloads: false
google_analytics: UA-57157948-2
theme: jekyll-theme-architect
header_pages:
  - index.md
  - the-bdverse-team.md
