title: The bdverse
description: Collection of R packages for biodiversity data
show_downloads: false
google_analytics: UA-57157948-2
theme: jekyll-theme-architect
header_pages:
  - index.md
  - the-bdverse-team.md
